// <auto-generated />
using CyberSpaceGamers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberSpaceGamers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251026214331_SeedProductTable")]
    partial class SeedProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyberSpaceGamers.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRating = "18+",
                            Genre = "Action",
                            Name = "Game One",
                            Price = 10.99m,
                            ShortDescription = "Game One Description"
                        },
                        new
                        {
                            Id = 2,
                            AgeRating = "12+",
                            Genre = "Adventure",
                            Name = "Game Two",
                            Price = 11.99m,
                            ShortDescription = "Game Two Description"
                        },
                        new
                        {
                            Id = 3,
                            AgeRating = "18+",
                            Genre = "RPG",
                            Name = "Game Three",
                            Price = 10.99m,
                            ShortDescription = "Game Three Description"
                        },
                        new
                        {
                            Id = 4,
                            AgeRating = "12+",
                            Genre = "Indie",
                            Name = "Game Four",
                            Price = 11.99m,
                            ShortDescription = "Game Four Description"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
