// <auto-generated />
using CyberSpaceGamers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberSpaceGamers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029181525_SeedProductTable")]
    partial class SeedProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyberSpaceGamers.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRating = "16+",
                            Genre = "Shooter",
                            Name = "BattleField 6",
                            Price = 59.99m,
                            ShortDescription = "Guns go pew pew woohoo"
                        },
                        new
                        {
                            Id = 2,
                            AgeRating = "18+",
                            Genre = "Survival",
                            Name = "Resident Evil Village",
                            Price = 25.99m,
                            ShortDescription = "If you know, you know"
                        },
                        new
                        {
                            Id = 3,
                            AgeRating = "16+",
                            Genre = "Horror",
                            Name = "Little Nightmares III",
                            Price = 49.00m,
                            ShortDescription = "Puny people fight larger nightmares"
                        },
                        new
                        {
                            Id = 4,
                            AgeRating = "12+",
                            Genre = "Fighter",
                            Name = "Super Smash Bros Ultimate",
                            Price = 54.50m,
                            ShortDescription = "King K rool players are evil. ps - Sora is better."
                        },
                        new
                        {
                            Id = 5,
                            AgeRating = "16+",
                            Genre = "Action",
                            Name = "Guardians of the Galaxy",
                            Price = 19.99m,
                            ShortDescription = "Groot is best Guardian. I am GRROOOT"
                        },
                        new
                        {
                            Id = 6,
                            AgeRating = "12+",
                            Genre = "Adventure",
                            Name = "Fallout 4",
                            Price = 11.99m,
                            ShortDescription = "Explore to your earnest galore"
                        },
                        new
                        {
                            Id = 7,
                            AgeRating = "14+",
                            Genre = "Action",
                            Name = "Saraj: Shadow Rebellion",
                            Price = 20.00m,
                            ShortDescription = "This game includes super Suraj"
                        },
                        new
                        {
                            Id = 8,
                            AgeRating = "14+",
                            Genre = "Multiplayer",
                            Name = "Josh: Empires Unite",
                            Price = 20.99m,
                            ShortDescription = "This game includes The organised Joshua of Laws"
                        },
                        new
                        {
                            Id = 9,
                            AgeRating = "14+",
                            Genre = "Adventure",
                            Name = "Dhruvisha’s Journey",
                            Price = 20.99m,
                            ShortDescription = "This game includes the determined Dhruvisha"
                        },
                        new
                        {
                            Id = 10,
                            AgeRating = "14+",
                            Genre = "Horror",
                            Name = "Whispering Woods: Kanwal’s Secret",
                            Price = 20.99m,
                            ShortDescription = "This game includes the Scary Kanwal"
                        },
                        new
                        {
                            Id = 11,
                            AgeRating = "14+",
                            Genre = "Mystery",
                            Name = "Crimson Evidence: Cameron Chronicles",
                            Price = 20.99m,
                            ShortDescription = "This game includes the big mouth but bigger heart jokester Cameron (Ps Best game here.)"
                        },
                        new
                        {
                            Id = 12,
                            AgeRating = "14+",
                            Genre = "Strategic",
                            Name = "Liar's Bar",
                            Price = 5.99m,
                            ShortDescription = "Be strategic and sly or die"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
